### PR TITLE
Add link to STLs uploaded to thingaverse

### PR DESCRIPTION
**Pull request by bruceme**
I uploaded your 4x5 STLs to Thingiverse and baught a print.  It is open license with the same artwork license you used here.  If you want a link to it on your readme, merge this pull request.

### CODE REVIEW

**Comment by tshort** [comment]
Im interested to hear how it works out.

**Comment by bruceme** [comment]
Me too will do

**Comment by bruceme** [comment]
It's done printing and has shipped today.  $28 from Treatstock 3D Printing
Network.  What a deal!  I've built an ergodox. I loved the robust the
keymapping, but it had too many silly keys and I want my Kinensis curve
back.  I was very impressed by the Dactyl, but it was complicated to make
and still had too many keys.  I really love what you've done, it's a big
evolution.  Nice work!

One more thing I like that you did was the magnet wire and daisy-chaining
the diode leads, I had the exact same idea looking at the original
Dactyle.  I will shamelessly steal that. I buy Pro-Micro's by the 10's and
have many handy, so this is a slam dunk project.

Need to make a key mapper generator like Ergodox.  I may help if I find the
time (I'm overwhelmed with project)

**Comment by bruceme** [comment]
Just got it.  Overall, it looks bit "Maker" but good enough, I'll try
acetone softening it.  The fit it poor, I will likely have to carve the key
holes larger.  But hey, it's kewl and I can't wait to get the real browns
and get this going.

**Comment by tshort** [comment]
Too bad on the fit. Of the four halves I've printed, the fit of the keys was quite good. I only had to expand about four key holes. The design by adereth worked great. I used PLA. I assume yours were ABS since you mentioned acetone.

On the wiring, you'll need a hot soldering iron on the magnet wire. On mine I did that way, I don't think my iron was hot enough, so I ended up with several bad connections that I had to reheat. I struggled with the diode legs. It's tough to keep them still. If I try that again, I might try soldering the diodes together first. That way, I could use tape or something to hold them while soldering.

**Comment by bruceme** [comment]
I had the same problem with the iron not being hot enough to strip the
insulation on a couple wires. No biggy, but yeah.

Ill make pull requests for;

- wiring diagram, neads something to say how it works, like 4x5 skips the
first pin on the rows.
- alternative coder and kenesis friendly keyboard layout

The best news though... I wrote this email on my dactyle manuform and while
I'm still stumbling and bumbling on stuff like caps keys and symbols, it's
gone well overall.

- Bruce

**Comment by bruceme** [comment]
Also... right hand swaps the column older... ie it's left to right both
hands

**Comment by bruceme** [comment]
I'm using this keyboard a lot... I've never adapted to a radical keyboard
as fast as this one. It's very solid. I needed to get it a bit closer to a
Kinesis for me (it's what I know) but I like how it works in general.
 really well done

**Comment by tshort** [comment]
Thanks for the update, and thanks for the PR's. I'll take a look.

**Pull request merged**
